genres = {
    "relax": [
        "acoustic",
        "ambient",
        "chill",
        "downtempo",
        "new-age",
        "piano",
        "sleep",
        "trip-hop",
        "classical",
    ],
    "energetic": [
        "afrobeat",
        "anime",
        "breakbeat",
        "british",
        "dance",
        "detroit-techno",
        "j-dance",
        "j-idol",
        "j-pop",
        "j-rock",
        "k-pop",
        "party",
        "power-pop",
        "progressive-house",
        "road-trip",
        "rockabilly",
        "summer",
        "swedish",
        "techno",
        "trance",
        "work-out",
    ],
    "angry": [
        "black-metal",
        "death-metal",
        "grindcore",
        "hardcore",
        "punk",
        "punk-rock",
    ],
    "neutral": [
        "alternative",
        "jazz",
        "singer-songwriter",
        "classical",
        "indian classical",
    ],
    "surprise": ["bossanova", "disco", "show-tunes"],
    "happy": [
        "brazil",
        "cantopop",
        "comedy",
        "disco",
        "disney",
        "edm",
        "funk",
        "happy",
        "honky-tonk",
        "latin",
        "reggaeton",
        "rock-n-roll",
        "salsa",
        "sertanejo",
        "spanish",
        "world-music",
        "bollywood hits",
        "hollywood hits",
    ],
    "sad": [
        "blues",
        "emo",
        "folk",
        "grunge",
        "metal",
        "pop-film",
        "sad",
        "songwriter",
        "classical",
        "indian classical",
    ],
    "fear": ["ambient", "dark-ambient", "drone", "horror", "post-rock"],
    "disgust": ["grindcore", "hardcore"],
}
instrumental_genres = {
    "happy": [
        "instrumental-pop english",
        "instrumental-dance english",
        "instrumental-bollywood hits",
        "instrumental-hollywood hits",
        "instrumental songs",
        "instrumental-salsa spanish",
        "instrumental-cumbia spanish",
        "instrumental-chanson french",
        "instrumental-disco french",
        "instrumental-bollywood hindi",
        "instrumental-dhol hindi",
        "instrumental music",
    ],
    "sad": [
        "instrumental-piano",
        "instrumental-ambient",
        "instrumental ",
        "classical music",
        "silent",
        "instrumental-bolero",
        "instrumental-tango",
        "classical sad",
        "instrumental spanish classical",
        "instrumental-chanson",
        "instrumental-sad",
        "classical",
        "instrumental french classical",
        "instrumental-sad",
        "instrumental-flute",
        "instrumental classical",
        "instrumental indian classical",
    ],
    "relax": [
        "instrumental acoustic",
        "instrumental ambient",
        "instrumental chill",
        "instrumental downtempo",
        "instrumental new-age",
        "instrumental piano",
        "instrumental sleep",
        "instrumental trip-hop",
        "instrumental classical",
    ],
    "energetic": [
        "instrumental afrobeat",
        "instrumental anime",
        "instrumental breakbeat",
        "instrumental british",
        "instrumental dance",
        "instrumental detroit-techno",
        "instrumental j-dance",
        "instrumental j-idol",
        "instrumental j-pop",
        "instrumental j-rock",
    ],
    "angry": [
        "instrumental black-metal",
        "instrumental death-metal",
        "instrumental grindcore",
        "instrumental hardcore",
        "instrumental punk",
        "instrumental punk-rock",
    ],
    "neutral": [
        "instrumental alternative",
        "instrumental jazz",
        "instrumental singer-songwriter",
        "instrumental classical",
        "instrumental indian classical",
    ],
    "surprise": [
        "instrumental bossanova",
        "instrumental disco",
        "instrumental show-tunes",
    ],
    "fear": [
        "instrumental ambient",
        "instrumental dark-ambient",
        "instrumental drone",
        "instrumental horror",
        "instrumental post-rock",
    ],
    "disgust": ["instrumental grindcore", "instrumental hardcore"],
}
