SPOTIPY_CLIENT_ID = "2ae751452b6a4bb385f129aa2849e30a"
SPOTIPY_CLIENT_SECRET = "fcae1bab1b7d4cf7b3b537ca19ffcd6d"
SPOTIPY_REDIRECT_URI = 'https://github.com/MalanSale/emotion_player/blob/chilltrill_new/app_trial.py/callback'
